version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/buildSrc/src/main/kotlin"  # /buildSrc and /codegpt-telemetry use only references
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/codegpt-treesitter"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
